### PR TITLE
Add 1.21.4

### PR DESCRIPTION
**Pull request by ScribbleTAS**
- Update loom
- Removed spawnInvulnerability hack

### CODE REVIEW

**Comment by ScribbleTAS** [comment]
So it seems that Mojang removed spawn invulnerability in 1.21.4, which is a bold choice... This would kill the "invulnerability-checkbox" in LoTAS...

**Comment by ScribbleTAS** [comment]
Test

**Comment by PancakeTAS** [comment]
i don't have internet.. my github barely works, i just wanna point out there's .gitignores in subdirectories

**Comment by ScribbleTAS** [comment]
> i don't have internet.. my github barely works, i just wanna point out there's .gitignores in subdirectories

Fixed

**Review by PancakeTAS — APPROVED** [review]

**Pull request merged**
